#!/usr/bin/env python
""" Operations on optical media catalog.
    Shell script.
"""
import argparse
from yoyodyne import media


def add(args):
    media.add(args.path, args.label)


def search(args):
    media.search(args.term, field=args.field)


def eject(args):
    media.eject()


parser = argparse.ArgumentParser(description="""
Operations on the optical media library.
""")
subparsers = parser.add_subparsers(title='subcommands')

parser_add = subparsers.add_parser('add')
parser_add.add_argument('--label',
                        help='ignore volume label on media, use LABEL')
parser_add.add_argument('path',
                        help='path to media (name when dropped on shortcut)')
parser_add.set_defaults(func=add)

parser_search = subparsers.add_parser('search')
parser_search.add_argument('--field', default='file')
parser_search.add_argument('term',
                           help='search file and folder names for this term')
parser_search.set_defaults(func=search)

parser_eject = subparsers.add_parser('eject')
parser_eject.set_defaults(func=eject)

args = parser.parse_args()
args.func(args)
