#!/usr/bin/env python
"""
Shell command; operations on optical media catalog.
"""
import argparse
from yoyodyne import media


def add(args):
    media.add(args.path, args.label)


def discs(args):
    media.display(media.discs())


def eject(args):
    media.eject()


def files(args):
    media.display(media.files(args.id))

    
def search(args):
    media.display(media.search(args.term, field=args.field))


parser = argparse.ArgumentParser(description="""
Operations on the optical media library.
""")
subparsers = parser.add_subparsers(title='subcommands')

parser_add = subparsers.add_parser('add')
parser_add.add_argument('--label',
                        help='ignore volume label on media, use LABEL')
parser_add.add_argument('path',
                        help='path to media (name when dropped on shortcut)')
parser_add.set_defaults(func=add)

subparser = subparsers.add_parser('discs')
subparser.set_defaults(func=discs)

subparser = subparsers.add_parser('files')
subparser.add_argument('id',
                        help='this disc ID')
subparser.set_defaults(func=files)

parser_search = subparsers.add_parser('search')
parser_search.add_argument('--field', default='file')
parser_search.add_argument('term',
                           help='search file and folder names for this term')
parser_search.set_defaults(func=search)

parser_eject = subparsers.add_parser('eject')
parser_eject.set_defaults(func=eject)

args = parser.parse_args()
args.func(args)
