#!/usr/bin/python
"""
    Operations on optical media catalog.
    Shell script.
"""
import argparse
import sys
from optparse import OptionParser
import media

parser = argparse.ArgumentParser(description="""
Operations on the optical media library.
""")
subparsers = parser.add_subparsers(title='subcommands')

def add(args):
    label = None
    if args.label:
        label = options.label
    media.add(args, label)
    command = sys.argv[1]

parser_add = subparsers.add_parser('add')
parser_add.add_argument('--label', help='ignore volume label on media, use LABEL')
parser_add.set_defaults(func=add)

def search(args):
    media.search(args.term)

parser_search = subparsers.add_parser('search')
parser_search.add_argument('term', help='search file and folder names for this term')
parser_search.set_defaults(func=search)

def eject(args):
    media.eject(args)

parser_eject = subparsers.add_parser('eject')
parser_eject.set_defaults(func=eject)

args = parser.parse_args()
args.func(args)

