#!/usr/bin/env python2.7
''' A PySide version of hello Qt. ''' 
# Import PySide classes
import sys
from PySide.QtCore import *
from PySide.QtGui import *
 
# Create a Qt application
app = QApplication(sys.argv)

window = QWidget()

# Create a Label and show it
label = QLabel("Hello World")
button = QPushButton("Press Me")

layout = QHBoxLayout()
layout.addWidget(label)
layout.addWidget(button)
window.setLayout(layout)
window.show()

# Enter Qt application main loop
app.exec_()
sys.exit()

