#!/usr/bin/python
"""
    Operations on media library index.
    Shell script.
"""
import sys
from optparse import OptionParser
from twiddlets import media

parser = OptionParser(usage="""
media <command> <command-args>

Operations on the optical media library.

Commands:
  add <name>        add disc in drive to the library, as <name>
  search <term>     print any rows in the library containing term
  eject             eject disc
""")
(options,args) = parser.parse_args()

if len(args) < 1:
    parser.print_help()
    exit(1)

command = sys.argv[1]
if command == 'search':
    media.search(sys.argv[2:])
elif command == 'add':
    media.add(sys.argv[2:])
elif command == 'eject':
    media.eject(sys.argv[2:])
else:
    print 'Error, unsupported command "%s"' % command
